# ----------------------------------------
# プロファイルの切り替え
# ここに記述された内容は application.ymlの内容より優先
# 後勝ち
# ----------------------------------------
spring.profiles.group:
  local:
    - local

server:
  port: 8080

# ----------------------------------------
# logging
# ----------------------------------------
logging:
  level:
    org:
      springframework: INFO
      springframework.boot: INFO
      springframework.boot.devtools: INFO
      springframework.jdbc: INFO
    com.uyawer:
      portal: INFO
      portal.repository: INFO

# ----------------------------------------
# DataSource
# ----------------------------------------
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://{hostname}:{port}/{schema]
  username:
  password:

# ----------------------------------------
# JPA
# ----------------------------------------
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: validate
  open-in-view: true
  hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ----------------------------------------
# WEB
# ----------------------------------------
spring.web:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

# ----------------------------------------
# MVC
# ----------------------------------------
spring.mvc:
  hiddenmethod:
    filter:
      enabled: true # formでput/deleteを使うための設定
