version: '3.7'
services:
  postgresql:
    image: postgres:14.4
    ports:
      - 15432:5432
    container_name: portal-db
    networks:
      - portal-network
    volumes:
      - portal-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: portaluser
      POSTGRES_PASSWORD: portaluser0428
      POSTGRES_DB: portal
    restart: always

volumes:
  portal-db-volume:
    external: true

networks:
  default:
    external:
      name: bridge
  portal-network:
    name: portal-docker-network
